# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""RCI (Refactoring Coherence Index) harness.
Measures (locality, paraphrase-invariance, propagation-depth) of a
forced knowledge edit — the MEMIT/AlphaEdit 3-axis protocol."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, List

@dataclass
class EditReport:
    locality:       float   # 0..1 (off-topic unchanged)
    paraphrase_inv: float   # 0..1 (rephrased query same answer)
    propagation:    float   # 0..1 (downstream inferences updated)

    def rci(self) -> float:
        return 0.40*self.propagation + 0.35*self.paraphrase_inv + 0.25*self.locality

def evaluate_edit(before: Dict[str,str], after: Dict[str,str],
                  off_topic: List[str],
                  paraphrases: List[str],
                  downstream: List[str]) -> EditReport:
    preserved = sum(1 for q in off_topic if before.get(q) == after.get(q))
    loc = preserved / max(1, len(off_topic))

    same_answer = sum(1 for q in paraphrases if after.get(q) == after.get(paraphrases[0]))
    par = same_answer / max(1, len(paraphrases))

    propagated = sum(1 for q in downstream if after.get(q) != before.get(q))
    prop = propagated / max(1, len(downstream))

    return EditReport(locality=loc, paraphrase_inv=par, propagation=prop)
