# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Heterogeneous judge ensemble — aggregates verdicts from
multiple backends with a diversity bonus for model-family spread."""
from __future__ import annotations
from dataclasses import dataclass
from typing import List

@dataclass
class JudgeVerdict:
    family: str          # "anthropic" | "openai" | "google" | "local"
    verdict: str         # "pass" | "review" | "block"
    score:   float       # 0..1

def consensus(verdicts: List[JudgeVerdict]) -> dict:
    if not verdicts:
        return {"verdict":"review","score":0.0,"families":0}
    fams = {v.family for v in verdicts}
    from collections import Counter
    tally = Counter(v.verdict for v in verdicts)
    top, count = tally.most_common(1)[0]
    score = sum(v.score for v in verdicts if v.verdict == top) / max(1, count)
    diversity_bonus = min(0.15, 0.05 * (len(fams) - 1))
    return {"verdict": top,
            "score": min(1.0, score + diversity_bonus),
            "families": len(fams)}
