#!/usr/bin/env bash
# ns_worker_boot_commands.sh — Start worker-tier models via vLLM
# Generated by ns_max_complete_models.sh v1.1.0 on 20260423_144703
#
# CAUTION: Worker models require a GPU node or substantial RAM.
# Do NOT run all workers simultaneously on the same Mac serving local_live MLX models.

set -euo pipefail

WORKERS_ROOT="/Volumes/NSExternal/models/workers"
VLLM_HOST="${VLLM_HOST:-0.0.0.0}"
VLLM_PORT_W1="${VLLM_PORT_W1:-8100}"
VLLM_PORT_W2="${VLLM_PORT_W2:-8101}"
VLLM_PORT_W3="${VLLM_PORT_W3:-8102}"

start_worker() {
  local name="$1"
  local model_path="$2"
  local port="$3"
  echo "Starting ${name} on :${port} ..."
  python -m vllm.entrypoints.openai.api_server \
    --model "${model_path}" \
    --host "${VLLM_HOST}" \
    --port "${port}" \
    --trust-remote-code \
    --dtype auto \
    &
  echo "  PID $! — ${name}"
}

case "${1:-all}" in
  W1|kimi)       start_worker "Kimi-K2.6"                 "${WORKERS_ROOT}/Kimi-K2.6"                   "${VLLM_PORT_W1}" ;;
  W2|deepseek)   start_worker "DeepSeek-V3.2"             "${WORKERS_ROOT}/DeepSeek-V3.2"               "${VLLM_PORT_W2}" ;;
  W3|qwen-vlm)   start_worker "Qwen3-VL-30B-A3B-Thinking" "${WORKERS_ROOT}/Qwen3-VL-30B-A3B-Thinking"  "${VLLM_PORT_W3}" ;;
  all)
    start_worker "Kimi-K2.6"                 "${WORKERS_ROOT}/Kimi-K2.6"                   "${VLLM_PORT_W1}"
    start_worker "DeepSeek-V3.2"             "${WORKERS_ROOT}/DeepSeek-V3.2"               "${VLLM_PORT_W2}"
    start_worker "Qwen3-VL-30B-A3B-Thinking" "${WORKERS_ROOT}/Qwen3-VL-30B-A3B-Thinking"  "${VLLM_PORT_W3}"
    ;;
  *)
    echo "Usage: $0 [W1|W2|W3|kimi|deepseek|qwen-vlm|all]"
    exit 1
    ;;
esac

echo ""
echo "Workers started. Use 'kill %1 %2 %3' or pkill -f vllm to stop."
