# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""ConfTuner — tokenized-Brier calibration trainer (Li et al. 2025 style).
Implements the per-token Brier loss for (output, confidence) pairs
and exposes the hook-point where a fine-tune SFT pass plugs in."""
from __future__ import annotations
from dataclasses import dataclass
from typing import List, Tuple

@dataclass
class ConfSample:
    pred_token: str
    gold_token: str
    confidence: float   # 0..1

def tokenized_brier(samples: List[ConfSample]) -> float:
    if not samples: return 0.0
    total = 0.0
    for s in samples:
        y = 1.0 if s.pred_token == s.gold_token else 0.0
        total += (s.confidence - y) ** 2
    return total / len(samples)

def ece(samples: List[ConfSample], bins: int = 10) -> float:
    if not samples: return 0.0
    buckets: List[List[Tuple[float, float]]] = [[] for _ in range(bins)]
    for s in samples:
        idx = min(int(s.confidence * bins), bins - 1)
        y = 1.0 if s.pred_token == s.gold_token else 0.0
        buckets[idx].append((s.confidence, y))
    n = len(samples)
    e = 0.0
    for b in buckets:
        if not b: continue
        conf = sum(x[0] for x in b) / len(b)
        acc  = sum(x[1] for x in b) / len(b)
        e += (len(b) / n) * abs(conf - acc)
    return e

def trainer_hook(samples: List[ConfSample]) -> dict:
    """Returns the loss payload an SFT trainer consumes."""
    return {
        "loss_tokenized_brier": tokenized_brier(samples),
        "ece": ece(samples),
        "n": len(samples),
    }
