# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Hamiltonian-gate runtime assertion layer.
Every action routed through the Dignity Kernel carries an assertion;
coverage ≥0.85 is a constitutional precondition (I₅ Hamiltonian)."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Callable, Dict, Any

@dataclass
class Assertion:
    name: str
    predicate: Callable[[Dict[str, Any]], bool]
    critical: bool = True

@dataclass
class GateResult:
    ok: bool
    violations: List[str] = field(default_factory=list)

class HamiltonianGate:
    def __init__(self) -> None:
        self._asserts: List[Assertion] = []

    def register(self, a: Assertion) -> None:
        self._asserts.append(a)

    def evaluate(self, ctx: Dict[str, Any]) -> GateResult:
        viols = [a.name for a in self._asserts if not a.predicate(ctx)]
        return GateResult(ok=not viols, violations=viols)

    def coverage(self, routed_actions: int) -> float:
        if routed_actions <= 0: return 0.0
        return min(1.0, len(self._asserts) / max(1, routed_actions))

GATE = HamiltonianGate()
GATE.register(Assertion("no_bypass",          lambda c: c.get("route") == "dignity"))
GATE.register(Assertion("receipt_emitted",    lambda c: bool(c.get("receipt_hash"))))
GATE.register(Assertion("never_event_checked",lambda c: c.get("ne_checked") is True))
GATE.register(Assertion("actor_authenticated",lambda c: bool(c.get("actor"))))
GATE.register(Assertion("monotone_supersede", lambda c: c.get("delete") is not True))
