# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Reversible-computation registry.
Tracks which NS∞ state transitions carry an explicit inverse,
enabling bisimulation-with-replay (2-safety)."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Callable, Dict, Any, Tuple

Transition = Callable[[Any], Any]

@dataclass
class ReversibleOp:
    name: str
    forward: Transition
    inverse: Transition

class ReversibleRegistry:
    def __init__(self) -> None:
        self._ops: Dict[str, ReversibleOp] = {}

    def register(self, name: str, fwd: Transition, inv: Transition) -> None:
        self._ops[name] = ReversibleOp(name, fwd, inv)

    def roundtrip(self, name: str, state: Any) -> Tuple[Any, Any, bool]:
        op = self._ops[name]
        after = op.forward(state)
        back = op.inverse(after)
        return after, back, back == state

    def coverage(self, total_transition_count: int) -> float:
        if total_transition_count <= 0: return 0.0
        return min(1.0, len(self._ops) / total_transition_count)

# NS∞ canonical reversible operations (illustrative — extend in domain code)
def _default_registry() -> ReversibleRegistry:
    r = ReversibleRegistry()
    r.register("identity", lambda s: s,                  lambda s: s)
    r.register("append",   lambda s: s + (0,),           lambda s: s[:-1])
    r.register("increment",lambda s: s + 1,              lambda s: s - 1)
    r.register("toggle",   lambda s: not s,              lambda s: not s)
    return r

DEFAULT = _default_registry()
