# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Witness-cosign triad — 3 independent witnesses cosign every
Alexandria STH (signed tree head), RFC 9162-style. When any two
witnesses disagree, the STH is marked `disputed` and HIC is required.
Pure in-process signing for local runs; real deployment wires
Sigstore Rekor v2 / witness.dev / independent third witness."""
from __future__ import annotations
import hashlib, hmac, json, time, os
from dataclasses import dataclass, asdict
from typing import List, Dict, Any

WITNESS_KEYS = {
    "alpha":  os.environ.get("NS_WITNESS_ALPHA_KEY",  "alpha-dev-key").encode(),
    "beta":   os.environ.get("NS_WITNESS_BETA_KEY",   "beta-dev-key").encode(),
    "gamma":  os.environ.get("NS_WITNESS_GAMMA_KEY",  "gamma-dev-key").encode(),
}

@dataclass
class SignedTreeHead:
    tree_size: int
    root_hash: str
    timestamp: float
    cosigns: Dict[str, str]   # witness_id → hex hmac

    def to_json(self) -> str:
        return json.dumps(asdict(self), sort_keys=True)

    def is_quorate(self, required: int = 3) -> bool:
        return len([c for c in self.cosigns.values() if c]) >= required

def _sign(key: bytes, payload: bytes) -> str:
    return hmac.new(key, payload, hashlib.sha256).hexdigest()

def build_sth(tree_size: int, root_hash: str, ts: float | None = None) -> SignedTreeHead:
    ts = ts if ts is not None else time.time()
    payload = f"{tree_size}|{root_hash}|{ts}".encode()
    cosigns = {wid: _sign(k, payload) for wid, k in WITNESS_KEYS.items()}
    return SignedTreeHead(tree_size=tree_size, root_hash=root_hash,
                          timestamp=ts, cosigns=cosigns)

def verify_sth(sth: SignedTreeHead) -> Dict[str, Any]:
    payload = f"{sth.tree_size}|{sth.root_hash}|{sth.timestamp}".encode()
    status = {}
    agree = 0
    for wid, k in WITNESS_KEYS.items():
        expected = _sign(k, payload)
        ok = hmac.compare_digest(expected, sth.cosigns.get(wid, ""))
        status[wid] = ok
        if ok:
            agree += 1
    return {"agree": agree, "required": 3, "ok": agree >= 3, "per_witness": status}
