# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""SLSA/in-toto build provenance attestation (offline-friendly).
Produces a JSON blob compatible with the in-toto statement schema
and verifies it."""
from __future__ import annotations
import hashlib, json, os, time
from dataclasses import dataclass, asdict
from typing import Dict, List

@dataclass
class Subject:
    name: str
    digest_sha256: str

@dataclass
class Statement:
    _type: str
    predicateType: str
    subject: List[Subject]
    predicate: Dict[str, str]

def build_statement(subject_name: str, data: bytes,
                    builder_id: str = "axiolev/ceiling-ci") -> dict:
    sub = Subject(name=subject_name,
                  digest_sha256=hashlib.sha256(data).hexdigest())
    stmt = Statement(
        _type="https://in-toto.io/Statement/v1",
        predicateType="https://slsa.dev/provenance/v1",
        subject=[sub],
        predicate={"builder_id": builder_id,
                   "build_type": "axiolev/ceiling-v1",
                   "build_time": str(int(time.time()))},
    )
    s = {"_type": stmt._type, "predicateType": stmt.predicateType,
         "subject": [asdict(sub)], "predicate": stmt.predicate}
    return s

def verify_statement(stmt: dict, data: bytes) -> bool:
    got = hashlib.sha256(data).hexdigest()
    return any(s["digest_sha256"] == got for s in stmt["subject"])
