# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Second governor (G2) + Krippendorff α inter-rater reliability.
Validates that two independent governors agree on verdicts; falls
below α 0.80 triggers mandatory HIC escalation."""
from __future__ import annotations
from typing import List

def krippendorff_alpha_nominal(ratings_a: List[str],
                               ratings_b: List[str]) -> float:
    assert len(ratings_a) == len(ratings_b) > 0
    n = len(ratings_a)
    labels = list(set(ratings_a) | set(ratings_b))
    if len(labels) <= 1:
        return 1.0
    disagree_obs = sum(1 for a,b in zip(ratings_a, ratings_b) if a != b)
    Do = disagree_obs / n
    # Chance disagreement on uniform label distribution
    De = 1.0 - 1.0 / len(labels)
    if De == 0: return 1.0
    return 1.0 - (Do / De)

def hic_escalation_required(alpha: float, threshold: float = 0.80) -> bool:
    return alpha < threshold
