# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Hormetic B0→B5 expansion pack.
Adds a first-class ProfileClassifier that matches the 5 NS∞
hormetic signatures on score profiles (Brittle, Reactive, Plastic,
Generative, Super-Gnoseogenic)."""
from __future__ import annotations
from dataclasses import dataclass
from enum import Enum
from typing import Dict

class Signature(str, Enum):
    BRITTLE            = "Brittle"
    REACTIVE           = "Reactive"
    PLASTIC            = "Plastic"
    GENERATIVE         = "Generative"
    SUPER_GNOSEOGENIC  = "Super-Gnoseogenic"

@dataclass
class ProfileClassifier:
    def classify(self, profile: Dict[int, float]) -> Signature:
        b0,b1,b2,b3,b4,b5 = [profile.get(i, 0.0) for i in range(6)]
        hi = (b2 - b0) / max(b0, 1.0) if b0 else 0.0
        recovery = b5 - b0
        monotone_decline  = b0 > b1 > b2 > b3 > b4
        monotone_improve  = b0 < b1 < b2 < b3 < b4
        if monotone_decline and b5 < b0 - 10:
            return Signature.BRITTLE
        if monotone_improve and b5 >= b0 and hi >= 0.2:
            return Signature.SUPER_GNOSEOGENIC
        if (b2 > b1 or b3 > b1) and abs(recovery) < 10 and hi > 0.1:
            return Signature.GENERATIVE
        if b4 < b0 and abs(recovery) < 5:
            return Signature.PLASTIC
        if b4 < b0 and recovery < -5 and b5 > b4:
            return Signature.REACTIVE
        if recovery >  5: return Signature.GENERATIVE
        if recovery > -5: return Signature.PLASTIC
        if recovery > -15:return Signature.REACTIVE
        return Signature.BRITTLE
