# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Alexandria Merkle transparency log — RFC 9162-style.
Append-only log with inclusion proofs. Pure Python; audit-grade."""
from __future__ import annotations
import hashlib
from typing import List, Tuple

def h(b: bytes) -> bytes:    return hashlib.sha256(b).digest()
def leaf(b: bytes) -> bytes: return h(b"\x00" + b)
def inner(l: bytes, r: bytes) -> bytes: return h(b"\x01" + l + r)

class MerkleLog:
    def __init__(self) -> None:
        self._leaves: List[bytes] = []

    def append(self, entry: bytes) -> int:
        self._leaves.append(leaf(entry))
        return len(self._leaves) - 1

    def size(self) -> int:
        return len(self._leaves)

    def _root_of(self, hashes: List[bytes]) -> bytes:
        if not hashes: return h(b"")
        level = list(hashes)
        while len(level) > 1:
            nxt = []
            for i in range(0, len(level), 2):
                if i + 1 < len(level):
                    nxt.append(inner(level[i], level[i+1]))
                else:
                    nxt.append(level[i])
            level = nxt
        return level[0]

    def root(self) -> str:
        return self._root_of(self._leaves).hex()

    def inclusion_proof(self, index: int) -> List[str]:
        assert 0 <= index < len(self._leaves)
        path: List[bytes] = []
        level = list(self._leaves)
        idx = index
        while len(level) > 1:
            nxt = []
            for i in range(0, len(level), 2):
                if i + 1 < len(level):
                    pair = (level[i], level[i+1])
                    if i == (idx ^ 1) or i + 1 == (idx ^ 1):
                        path.append(pair[1] if idx % 2 == 0 else pair[0])
                    nxt.append(inner(*pair))
                else:
                    nxt.append(level[i])
            idx //= 2
            level = nxt
        return [x.hex() for x in path]

    def verify_inclusion(self, entry: bytes, index: int,
                         proof: List[str], root_hex: str) -> bool:
        cur = leaf(entry)
        idx = index
        for sib_hex in proof:
            sib = bytes.fromhex(sib_hex)
            cur = inner(cur, sib) if idx % 2 == 0 else inner(sib, cur)
            idx //= 2
        return cur.hex() == root_hex
