# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Apollo counterweight — awareness-token downgrade.
If telemetry shows the system claiming a confidence or capability
it has no evidence for, downgrade the score.  Prevents Goodhart."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Dict

@dataclass
class EvidenceTelemetry:
    claimed_confidence: float
    observed_accuracy:  float
    receipts_present:   bool

def downgrade_factor(t: EvidenceTelemetry) -> float:
    # If claims outrun evidence, clamp
    gap = max(0.0, t.claimed_confidence - t.observed_accuracy)
    base = 1.0 - min(1.0, gap * 1.5)
    if not t.receipts_present:
        base *= 0.8
    return max(0.0, min(1.0, base))

def adjusted(score: float, t: EvidenceTelemetry) -> float:
    return max(0.0, min(100.0, score * downgrade_factor(t)))
