# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""MCI — MDL Compression Improvement.
Measures pre/post-stress description-length ratio as a Kolmogorov proxy
using bzip2 compression.  Belt-bloat (LLM memorization) tanks MCI;
core-compression (CPS Calculus) raises it."""
from __future__ import annotations
import bz2

def mdl_bits(payload: bytes) -> int:
    return 8 * len(bz2.compress(payload, 9))

def mci(pre: bytes, post: bytes) -> float:
    b_pre  = mdl_bits(pre)
    b_post = mdl_bits(post)
    if b_pre == 0: return 0.0
    return max(0.0, (b_pre - b_post) / b_pre)
