# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Replay-operator soundness proof.
A receipt-chain replay is sound iff replaying the log from genesis
reproduces the current state byte-for-byte (bisimulation with replay)."""
from __future__ import annotations
import hashlib, json
from typing import List, Dict, Any

def _hash(s: str) -> str:
    return hashlib.sha256(s.encode()).hexdigest()

def apply_events(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    state: Dict[str, Any] = {"counter": 0, "keys": {}}
    for e in events:
        t = e.get("type")
        if t == "inc":
            state["counter"] += int(e.get("by", 1))
        elif t == "set":
            state["keys"][e["k"]] = e["v"]
        elif t == "del" and e["k"] in state["keys"]:
            # supersession monotone — we mark, do not delete
            state["keys"][e["k"]] = None
    return state

def replay_fingerprint(events: List[Dict[str, Any]]) -> str:
    return _hash(json.dumps(apply_events(events), sort_keys=True))

def replay_sound(events_genesis: List[Dict[str, Any]],
                 events_now:     List[Dict[str, Any]]) -> bool:
    return replay_fingerprint(events_genesis) == replay_fingerprint(events_now)
