# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""AURC (area under risk-coverage) + Chow selective prediction.
Standard tooling for calibrated abstention."""
from __future__ import annotations
from typing import List, Tuple

def risk_coverage_curve(confidences: List[float],
                        correctness: List[int]) -> List[Tuple[float, float]]:
    assert len(confidences) == len(correctness)
    pairs = sorted(zip(confidences, correctness), key=lambda x: -x[0])
    n = len(pairs)
    curve: List[Tuple[float, float]] = []
    errors = 0
    for i, (_, c) in enumerate(pairs, 1):
        if c == 0: errors += 1
        coverage = i / n
        risk = errors / i
        curve.append((coverage, risk))
    return curve

def aurc(confidences: List[float], correctness: List[int]) -> float:
    curve = risk_coverage_curve(confidences, correctness)
    if len(curve) < 2: return 0.0
    area = 0.0
    for i in range(1, len(curve)):
        x0, y0 = curve[i-1]
        x1, y1 = curve[i]
        area += (x1 - x0) * (y0 + y1) / 2
    return area

def chow_tau_abstain(conf: float, tau: float) -> bool:
    return conf < tau
