# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Robustness perturbation suite — measures stability of an
answer function under character/semantic/order perturbations."""
from __future__ import annotations
from typing import Callable, List

def perturb_casing(s: str) -> str:   return s.swapcase()
def perturb_spaces(s: str) -> str:   return " ".join(s.split())
def perturb_reverse(s: str) -> str:  return s[::-1]
def perturb_noise(s: str) -> str:    return s + "   "

PERTURBS = [perturb_casing, perturb_spaces, perturb_reverse, perturb_noise]

def stability(answer_fn: Callable[[str], str], prompts: List[str]) -> float:
    if not prompts: return 1.0
    hits = 0; total = 0
    for p in prompts:
        base = answer_fn(p)
        for pz in PERTURBS:
            if pz is perturb_reverse:
                continue   # semantic-breaking; excluded from stability
            got = answer_fn(pz(p))
            total += 1
            if got == base:
                hits += 1
    return hits / total if total else 1.0
