#!/usr/bin/env python3
"""
NORTHSTAR Setup — Credential Loader
NS∞ / AXIOLEV Holdings

Run this ONCE before omega_boot.sh.
Opens a local browser UI at http://localhost:9001
Paste your key block → validates → writes ~/NSS/.env securely.

Nothing leaves your machine.
No network calls during setup.
Keys stored at ~/NSS/.env (chmod 600).

Usage:
    python3 ~/NSS/ns_setup.py
"""

import os
import re
import sys
import json
import hmac
import hashlib
import subprocess
import webbrowser
import threading
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse

ENV_PATH = Path.home() / "NSS" / ".env"
PORT = 9001

# ── Key patterns ─────────────────────────────────────────────────────────────
KEY_PATTERNS = {
    "ANTHROPIC_API_KEY":  r"sk-ant-[A-Za-z0-9_\-]{80,}",
    "OPENAI_API_KEY":     r"sk-proj-[A-Za-z0-9_\-]{80,}",
    "GOOGLE_API_KEY":     r"AIza[A-Za-z0-9_\-]{35}",
    "GROK_API_KEY":       r"xai-[A-Za-z0-9]{80,}",
    "TWILIO_ACCOUNT_SID": r"AC[a-f0-9]{32}",
    "TWILIO_AUTH_TOKEN":  r"[a-f0-9]{32}",
    "TWILIO_PHONE_NUMBER":r"\+1[\s\(]?[0-9]{3}[\s\)\-]?[0-9]{3}[\s\-]?[0-9]{4}",
    "POLYGON_API_KEY":    r"[A-Za-z0-9_]{20,}",
    "FRED_API_KEY":       r"[a-f0-9]{32}",
    "NEWSAPI_KEY":        r"[a-f0-9]{32}",
    "ALPACA_API_KEY":     r"[A-Z0-9]{20}",
    "ALPACA_API_SECRET":  r"[A-Za-z0-9]{40,}",
}

REQUIRED = [
    "ANTHROPIC_API_KEY", "OPENAI_API_KEY", "TWILIO_ACCOUNT_SID",
    "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER",
]

OPTIONAL = [
    "GOOGLE_API_KEY", "GROK_API_KEY", "POLYGON_API_KEY",
    "FRED_API_KEY", "NEWSAPI_KEY", "ALPACA_API_KEY", "ALPACA_API_SECRET",
]

# ── Parser ────────────────────────────────────────────────────────────────────

def parse_key_block(text: str) -> dict:
    """
    Parse a raw paste of keys in any format:
      KEY=value
      ✓ KEY=value
      KEY: value
      value (detected by pattern)
    Returns dict of {KEY_NAME: value}.
    """
    found = {}
    lines = text.strip().splitlines()

    for line in lines:
        line = line.strip().lstrip("✓ ").strip()

        # Try KEY=value or KEY: value
        for sep in ["=", ":"]:
            if sep in line:
                parts = line.split(sep, 1)
                key_candidate = parts[0].strip().upper().replace(" ", "_")
                val = parts[1].strip()

                # Normalize key names
                key_map = {
                    "TWILIO_PHONE": "TWILIO_PHONE_NUMBER",
                    "ALPACA_BROKER": "ALPACA_API_KEY",
                    "SECRET": "ALPACA_API_SECRET",
                    "TWITTER": None,  # skip
                }
                if key_candidate in key_map:
                    key_candidate = key_map[key_candidate]

                if key_candidate and key_candidate in KEY_PATTERNS and val:
                    found[key_candidate] = val
                break

        # Try pattern matching for values without key names
        for key_name, pattern in KEY_PATTERNS.items():
            if key_name not in found:
                m = re.search(pattern, line)
                if m:
                    # Don't double-assign
                    val = m.group(0)
                    if val not in found.values():
                        found[key_name] = val

    # Clean phone number
    if "TWILIO_PHONE_NUMBER" in found:
        phone = re.sub(r"[^\d+]", "", found["TWILIO_PHONE_NUMBER"])
        if not phone.startswith("+"):
            phone = "+" + phone
        found["TWILIO_PHONE_NUMBER"] = phone

    return found


def validate_keys(keys: dict) -> dict:
    """Returns {key: "ok"|"missing"|"invalid"}"""
    results = {}
    for key in list(KEY_PATTERNS.keys()):
        if key not in keys:
            results[key] = "missing" if key in REQUIRED else "optional"
        else:
            pattern = KEY_PATTERNS[key]
            if re.search(pattern, keys[key]):
                results[key] = "ok"
            else:
                results[key] = "invalid"
    return results


def write_env(keys: dict) -> str:
    """Write .env file, chmod 600. Returns path."""
    ENV_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# NORTHSTAR ENVIRONMENT — NS∞ / AXIOLEV Holdings",
        f"# Generated by ns_setup.py — {__import__('datetime').datetime.now().isoformat()}",
        "# Constitutional governance: Ω Advisory Sovereignty Law",
        "",
        "# ─── LLM INTELLIGENCE LAYER ──────────────────────────────────",
        f"ANTHROPIC_API_KEY={keys.get('ANTHROPIC_API_KEY', '')}",
        f"OPENAI_API_KEY={keys.get('OPENAI_API_KEY', '')}",
        f"GOOGLE_API_KEY={keys.get('GOOGLE_API_KEY', '')}",
        f"GROK_API_KEY={keys.get('GROK_API_KEY', '')}",
        "",
        "# ─── TWILIO (VOICE — Computer Interface) ─────────────────────",
        f"TWILIO_ACCOUNT_SID={keys.get('TWILIO_ACCOUNT_SID', '')}",
        f"TWILIO_AUTH_TOKEN={keys.get('TWILIO_AUTH_TOKEN', '')}",
        f"TWILIO_PHONE_NUMBER={keys.get('TWILIO_PHONE_NUMBER', '')}",
        "",
        "# ─── TRADING — ALPACA ─────────────────────────────────────────",
        f"ALPACA_API_KEY={keys.get('ALPACA_API_KEY', '')}",
        f"ALPACA_API_SECRET={keys.get('ALPACA_API_SECRET', '')}",
        "ALPACA_BASE_URL=https://paper-api.alpaca.markets",
        "",
        "# ─── MARKET DATA ──────────────────────────────────────────────",
        f"POLYGON_API_KEY={keys.get('POLYGON_API_KEY', '')}",
        f"FRED_API_KEY={keys.get('FRED_API_KEY', '')}",
        f"NEWSAPI_KEY={keys.get('NEWSAPI_KEY', '')}",
        "",
        "# ─── SYSTEM ───────────────────────────────────────────────────",
        "NORTHSTAR_WEBHOOK_BASE=",
        "YUBIKEY_SERIAL=",
        "NS_ENV=production",
    ]

    ENV_PATH.write_text("\n".join(lines) + "\n")
    ENV_PATH.chmod(0o600)
    return str(ENV_PATH)

# ── macOS Keychain storage ────────────────────────────────────────────────────

def store_in_keychain(key_name: str, value: str):
    """Store a key in macOS Keychain as backup."""
    try:
        subprocess.run([
            "security", "add-generic-password",
            "-a", "northstar",
            "-s", f"northstar.{key_name.lower()}",
            "-w", value,
            "-U"  # update if exists
        ], capture_output=True, check=False)
    except Exception:
        pass  # Keychain optional


def store_all_in_keychain(keys: dict):
    """Store all keys in macOS Keychain."""
    for k, v in keys.items():
        if v:
            store_in_keychain(k, v)

# ── HTML UI ───────────────────────────────────────────────────────────────────

HTML = """<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>NORTHSTAR Setup</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body {
    background: #050d1a;
    color: #c8ddf0;
    font-family: 'JetBrains Mono', monospace;
    min-height: 100vh;
    padding: 40px 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .container { max-width: 720px; width: 100%; }
  h1 {
    font-size: 13px;
    letter-spacing: 5px;
    color: #00e87a;
    text-transform: uppercase;
    margin-bottom: 4px;
  }
  .sub {
    font-size: 10px;
    letter-spacing: 2px;
    color: #3a5570;
    margin-bottom: 40px;
  }
  .card {
    background: #080f1e;
    border: 1px solid #112240;
    border-radius: 4px;
    padding: 24px;
    margin-bottom: 20px;
  }
  .card-title {
    font-size: 9px;
    letter-spacing: 3px;
    color: #3a5570;
    text-transform: uppercase;
    margin-bottom: 14px;
  }
  textarea {
    width: 100%;
    height: 280px;
    background: #03080f;
    border: 1px solid #1a3a5e;
    border-radius: 3px;
    color: #c8ddf0;
    font-family: 'JetBrains Mono', monospace;
    font-size: 12px;
    padding: 14px;
    resize: vertical;
    outline: none;
    line-height: 1.6;
  }
  textarea:focus { border-color: #00e87a; }
  textarea::placeholder { color: #3a5570; }
  .btn {
    width: 100%;
    padding: 14px;
    background: #00e87a;
    color: #050d1a;
    border: none;
    border-radius: 3px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 3px;
    cursor: pointer;
    text-transform: uppercase;
    margin-top: 14px;
    transition: background 0.2s;
  }
  .btn:hover { background: #00ff88; }
  .btn:disabled { background: #1a3a5e; color: #3a5570; cursor: default; }
  .results { display: none; }
  .key-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 0;
    border-bottom: 1px solid #112240;
    font-size: 11px;
  }
  .key-row:last-child { border-bottom: none; }
  .key-name { color: #7090a8; min-width: 220px; }
  .key-status { font-size: 10px; letter-spacing: 1px; }
  .status-ok      { color: #00e87a; }
  .status-missing { color: #3a5570; }
  .status-optional{ color: #3a5570; }
  .status-invalid { color: #ff4455; }
  .path-box {
    background: #03080f;
    border: 1px solid #00e87a;
    border-radius: 3px;
    padding: 12px 14px;
    font-size: 12px;
    color: #00e87a;
    margin-top: 14px;
    word-break: break-all;
  }
  .next-steps {
    font-size: 11px;
    color: #7090a8;
    line-height: 2;
    margin-top: 14px;
  }
  .next-steps code {
    background: #0c1628;
    padding: 2px 6px;
    border-radius: 2px;
    color: #c8ddf0;
  }
  .warning {
    background: rgba(255,68,85,0.08);
    border: 1px solid rgba(255,68,85,0.3);
    border-radius: 3px;
    padding: 12px 14px;
    font-size: 11px;
    color: #ff8888;
    margin-bottom: 20px;
    line-height: 1.6;
  }
</style>
</head>
<body>
<div class="container">
  <h1>NORTHSTAR</h1>
  <div class="sub">NS∞ Credential Setup · Local Only · Nothing Leaves This Machine</div>

  <div class="warning">
    ⚠ Paste credentials ONLY here — never in chat interfaces, email, or notes apps.<br>
    This UI runs locally at localhost:9001. No network requests are made during setup.
  </div>

  <div class="card">
    <div class="card-title">Paste Your Key Block</div>
    <textarea id="keyblock" placeholder="Paste everything — any format works:
✓ ANTHROPIC_API_KEY=sk-ant-...
✓ OPENAI_API_KEY=sk-proj-...
✓ GOOGLE_API_KEY=AIza...
✓ GROK_API_KEY=xai-...
✓ TWILIO_ACCOUNT_SID=AC...
✓ TWILIO_AUTH_TOKEN=...
✓ TWILIO_PHONE=+1 (307) 202-4418
✓ POLYGON_API_KEY=...
✓ FRED_API_KEY=...
✓ NEWSAPI_KEY=...
Alpaca broker- KEY - secret - SECRET"></textarea>
    <button class="btn" onclick="parseAndWrite()" id="mainbtn">PARSE AND WRITE .ENV</button>
  </div>

  <div class="card results" id="results">
    <div class="card-title">Validation Results</div>
    <div id="key-list"></div>
    <div id="path-output"></div>
    <div class="next-steps" id="next-steps"></div>
  </div>
</div>

<script>
async function parseAndWrite() {
  const block = document.getElementById('keyblock').value.trim();
  if (!block) return;

  const btn = document.getElementById('mainbtn');
  btn.disabled = true;
  btn.textContent = 'PROCESSING...';

  try {
    const res = await fetch('/parse', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({block})
    });
    const data = await res.json();

    const resultsDiv = document.getElementById('results');
    resultsDiv.style.display = 'block';

    // Key list
    const keyList = document.getElementById('key-list');
    keyList.innerHTML = '';
    for (const [key, status] of Object.entries(data.validation)) {
      const row = document.createElement('div');
      row.className = 'key-row';
      const label = status === 'ok' ? '✓ FOUND' :
                    status === 'optional' ? '— OPTIONAL' :
                    status === 'missing'  ? '✗ MISSING' : '✗ INVALID';
      const cls = `status-${status}`;
      row.innerHTML = `<span class="key-name">${key}</span><span class="key-status ${cls}">${label}</span>`;
      keyList.appendChild(row);
    }

    if (data.written) {
      const pathBox = document.createElement('div');
      pathBox.className = 'path-box';
      pathBox.textContent = '✓ Written: ' + data.path;
      document.getElementById('path-output').appendChild(pathBox);

      document.getElementById('next-steps').innerHTML = `
        ✓ .env written and secured (chmod 600)<br>
        ✓ Keys stored in macOS Keychain<br><br>
        Next steps:<br>
        1. <code>~/NSS/omega_boot.sh</code><br>
        2. In new terminal: <code>ngrok http 9000</code><br>
        3. Paste ngrok URL → Twilio console → voice webhook<br>
        4. Call +13072024418 → "Computer online."<br><br>
        You can close this window.
      `;

      btn.textContent = '✓ WRITTEN — BOOT READY';
      btn.style.background = '#004422';
      btn.style.color = '#00e87a';
    } else {
      btn.disabled = false;
      btn.textContent = 'FIX ERRORS AND RETRY';
    }
  } catch(e) {
    btn.disabled = false;
    btn.textContent = 'ERROR — RETRY';
    console.error(e);
  }
}

// Paste handler — auto-submit on paste if block looks complete
document.getElementById('keyblock').addEventListener('paste', () => {
  setTimeout(() => {
    const val = document.getElementById('keyblock').value;
    if (val.includes('ANTHROPIC') && val.includes('TWILIO')) {
      document.getElementById('mainbtn').focus();
    }
  }, 100);
});
</script>
</body>
</html>"""

# ── HTTP Handler ──────────────────────────────────────────────────────────────

class SetupHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # Silent

    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.end_headers()
        self.wfile.write(HTML.encode())

    def do_POST(self):
        if self.path == "/parse":
            length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(length))
            block = body.get("block", "")

            keys = parse_key_block(block)
            validation = validate_keys(keys)
            written = False
            path = ""

            # Write if we have at least the required Anthropic key
            if keys.get("ANTHROPIC_API_KEY"):
                path = write_env(keys)
                store_all_in_keychain(keys)
                written = True

            result = json.dumps({
                "keys_found": list(keys.keys()),
                "validation": validation,
                "written": written,
                "path": path,
            })

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(result.encode())
        else:
            self.send_response(404)
            self.end_headers()


def shutdown_after(server, delay=300):
    """Auto-shutdown after 5 minutes for security."""
    import time
    time.sleep(delay)
    print("\n  Auto-shutdown (5min security timeout). Run again if needed.")
    server.shutdown()


if __name__ == "__main__":
    print()
    print("=" * 54)
    print("⚡ NORTHSTAR Setup — Credential Loader")
    print("   Local only. Nothing leaves this machine.")
    print("=" * 54)
    print()

    if ENV_PATH.exists():
        print(f"  ⚠  .env already exists at {ENV_PATH}")
        answer = input("     Overwrite? [y/N]: ").strip().lower()
        if answer != "y":
            print("  Cancelled.")
            sys.exit(0)

    server = HTTPServer(("127.0.0.1", PORT), SetupHandler)
    url = f"http://localhost:{PORT}"

    print(f"  → Opening {url}")
    print(f"  → Auto-closes in 5 minutes")
    print(f"  → Ctrl+C to exit early")
    print()

    threading.Thread(target=shutdown_after, args=(server,), daemon=True).start()
    threading.Timer(1.0, lambda: webbrowser.open(url)).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n  Closed.")
