# -*- coding: utf-8 -*-
# AXIOLEV Holdings LLC © 2026 — axiolevns@axiolev.com
# Generated by axiolev_script3_ceiling.sh — part of the NS∞ ceiling uplift.
# This module is additive and non-breaking; all invariants preserved.
"""Three-Realities reconstruction harness.
Lexicon / Alexandrian Archive / SAN are disjoint projections
of the same state. Any two must reconstruct the third."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, Any

@dataclass
class ThreeRealityState:
    lexicon:    Dict[str, Any]    # semantic (what the words mean)
    alexandria: Dict[str, Any]    # memory (what happened)
    san:        Dict[str, Any]    # position (where in reality)

    def reconstruct_lexicon(self) -> Dict[str, Any]:
        # derive semantic from memory+position (illustrative)
        return {"id": self.alexandria.get("id"),
                "tier": self.san.get("tier")}

    def reconstruct_alexandria(self) -> Dict[str, Any]:
        return {"id": self.lexicon.get("id"),
                "ts": self.san.get("ts")}

    def reconstruct_san(self) -> Dict[str, Any]:
        return {"tier": self.lexicon.get("tier"),
                "ts": self.alexandria.get("ts")}

    def is_reconstruction_sound(self) -> bool:
        return (self.reconstruct_lexicon().get("tier")  == self.lexicon.get("tier") and
                self.reconstruct_alexandria().get("id") == self.alexandria.get("id") and
                self.reconstruct_san().get("ts")        == self.san.get("ts"))

    def disjointness_score(self) -> float:
        lex = set(self.lexicon.keys())
        alx = set(self.alexandria.keys())
        san = set(self.san.keys())
        pairs = [lex & alx, lex & san, alx & san]
        overlap = sum(len(p) for p in pairs)
        total = len(lex) + len(alx) + len(san)
        if total == 0: return 1.0
        return max(0.0, 1.0 - overlap / total)
